// Daftar Kota/Kabupaten di Indonesia (Lengkap 514 Kab/Kota)
export const indonesiaCities = [
  // ACEH (23)
  "Kota Banda Aceh", "Kota Sabang", "Kota Langsa", "Kota Lhokseumawe", "Kota Subulussalam",
  "Kabupaten Aceh Besar", "Kabupaten Aceh Barat", "Kabupaten Aceh Barat Daya", "Kabupaten Aceh Jaya",
  "Kabupaten Aceh Selatan", "Kabupaten Aceh Singkil", "Kabupaten Aceh Tamiang", "Kabupaten Aceh Tengah",
  "Kabupaten Aceh Tenggara", "Kabupaten Aceh Timur", "Kabupaten Aceh Utara", "Kabupaten Bener Meriah",
  "Kabupaten Bireuen", "Kabupaten Gayo Lues", "Kabupaten Nagan Raya", "Kabupaten Pidie",
  "Kabupaten Pidie Jaya", "Kabupaten Simeulue",
  // SUMATERA UTARA (33)
  "Kota Medan", "Kota Binjai", "Kota Tebing Tinggi", "Kota Pematangsiantar", "Kota Tanjungbalai",
  "Kota Sibolga", "Kota Padang Sidempuan", "Kota Gunungsitoli",
  "Kabupaten Asahan", "Kabupaten Batubara", "Kabupaten Dairi", "Kabupaten Deli Serdang",
  "Kabupaten Humbang Hasundutan", "Kabupaten Karo", "Kabupaten Labuhanbatu", "Kabupaten Labuhanbatu Selatan",
  "Kabupaten Labuhanbatu Utara", "Kabupaten Langkat", "Kabupaten Mandailing Natal", "Kabupaten Nias",
  "Kabupaten Nias Barat", "Kabupaten Nias Selatan", "Kabupaten Nias Utara", "Kabupaten Padang Lawas",
  "Kabupaten Padang Lawas Utara", "Kabupaten Pakpak Bharat", "Kabupaten Samosir", "Kabupaten Serdang Bedagai",
  "Kabupaten Simalungun", "Kabupaten Tapanuli Selatan", "Kabupaten Tapanuli Tengah", "Kabupaten Tapanuli Utara",
  "Kabupaten Toba",
  // SUMATERA BARAT (19)
  "Kota Padang", "Kota Bukittinggi", "Kota Padang Panjang", "Kota Payakumbuh", "Kota Pariaman",
  "Kota Sawahlunto", "Kota Solok",
  "Kabupaten Agam", "Kabupaten Dharmasraya", "Kabupaten Kepulauan Mentawai", "Kabupaten Lima Puluh Kota",
  "Kabupaten Padang Pariaman", "Kabupaten Pasaman", "Kabupaten Pasaman Barat", "Kabupaten Pesisir Selatan",
  "Kabupaten Sijunjung", "Kabupaten Solok", "Kabupaten Solok Selatan", "Kabupaten Tanah Datar",
  // RIAU (12)
  "Kota Pekanbaru", "Kota Dumai",
  "Kabupaten Bengkalis", "Kabupaten Indragiri Hilir", "Kabupaten Indragiri Hulu", "Kabupaten Kampar",
  "Kabupaten Kepulauan Meranti", "Kabupaten Kuantan Singingi", "Kabupaten Pelalawan", "Kabupaten Rokan Hilir",
  "Kabupaten Rokan Hulu", "Kabupaten Siak",
  // KEPULAUAN RIAU (7)
  "Kota Batam", "Kota Tanjungpinang",
  "Kabupaten Bintan", "Kabupaten Karimun", "Kabupaten Kepulauan Anambas", "Kabupaten Lingga", "Kabupaten Natuna",
  // JAMBI (11)
  "Kota Jambi", "Kota Sungai Penuh",
  "Kabupaten Batanghari", "Kabupaten Bungo", "Kabupaten Kerinci", "Kabupaten Merangin",
  "Kabupaten Muaro Jambi", "Kabupaten Sarolangun", "Kabupaten Tanjung Jabung Barat",
  "Kabupaten Tanjung Jabung Timur", "Kabupaten Tebo",
  // SUMATERA SELATAN (17)
  "Kota Palembang", "Kota Lubuklinggau", "Kota Pagar Alam", "Kota Prabumulih",
  "Kabupaten Banyuasin", "Kabupaten Empat Lawang", "Kabupaten Lahat", "Kabupaten Muara Enim",
  "Kabupaten Musi Banyuasin", "Kabupaten Musi Rawas", "Kabupaten Musi Rawas Utara", "Kabupaten Ogan Ilir",
  "Kabupaten Ogan Komering Ilir", "Kabupaten Ogan Komering Ulu", "Kabupaten Ogan Komering Ulu Selatan",
  "Kabupaten Ogan Komering Ulu Timur", "Kabupaten Penukal Abab Lematang Ilir",
  // BENGKULU (10)
  "Kota Bengkulu",
  "Kabupaten Bengkulu Selatan", "Kabupaten Bengkulu Tengah", "Kabupaten Bengkulu Utara",
  "Kabupaten Kaur", "Kabupaten Kepahiang", "Kabupaten Lebong", "Kabupaten Mukomuko",
  "Kabupaten Rejang Lebong", "Kabupaten Seluma",
  // LAMPUNG (15)
  "Kota Bandar Lampung", "Kota Metro",
  "Kabupaten Lampung Barat", "Kabupaten Lampung Selatan", "Kabupaten Lampung Tengah", "Kabupaten Lampung Timur",
  "Kabupaten Lampung Utara", "Kabupaten Mesuji", "Kabupaten Pesawaran", "Kabupaten Pesisir Barat",
  "Kabupaten Pringsewu", "Kabupaten Tanggamus", "Kabupaten Tulang Bawang", "Kabupaten Tulang Bawang Barat",
  "Kabupaten Way Kanan",
  // BANGKA BELITUNG (7)
  "Kota Pangkalpinang",
  "Kabupaten Bangka", "Kabupaten Bangka Barat", "Kabupaten Bangka Selatan", "Kabupaten Bangka Tengah",
  "Kabupaten Belitung", "Kabupaten Belitung Timur",
  // DKI JAKARTA (6)
  "Kota Jakarta Pusat", "Kota Jakarta Utara", "Kota Jakarta Barat", "Kota Jakarta Selatan", "Kota Jakarta Timur",
  "Kabupaten Kepulauan Seribu",
  // JAWA BARAT (27)
  "Kota Bandung", "Kota Bekasi", "Kota Bogor", "Kota Cimahi", "Kota Cirebon", "Kota Depok",
  "Kota Sukabumi", "Kota Tasikmalaya", "Kota Banjar",
  "Kabupaten Bandung", "Kabupaten Bandung Barat", "Kabupaten Bekasi", "Kabupaten Bogor", "Kabupaten Ciamis",
  "Kabupaten Cianjur", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang",
  "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta",
  "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya",
  // BANTEN (8)
  "Kota Cilegon", "Kota Serang", "Kota Tangerang", "Kota Tangerang Selatan",
  "Kabupaten Lebak", "Kabupaten Pandeglang", "Kabupaten Serang", "Kabupaten Tangerang",
  // JAWA TENGAH (35)
  "Kota Semarang", "Kota Magelang", "Kota Pekalongan", "Kota Salatiga", "Kota Surakarta", "Kota Tegal",
  "Kabupaten Banjarnegara", "Kabupaten Banyumas", "Kabupaten Batang", "Kabupaten Blora", "Kabupaten Boyolali",
  "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Demak", "Kabupaten Grobogan", "Kabupaten Jepara",
  "Kabupaten Karanganyar", "Kabupaten Kebumen", "Kabupaten Kendal", "Kabupaten Klaten", "Kabupaten Kudus",
  "Kabupaten Magelang", "Kabupaten Pati", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Purbalingga",
  "Kabupaten Purworejo", "Kabupaten Rembang", "Kabupaten Semarang", "Kabupaten Sragen", "Kabupaten Sukoharjo",
  "Kabupaten Tegal", "Kabupaten Temanggung", "Kabupaten Wonogiri", "Kabupaten Wonosobo",
  // DI YOGYAKARTA (5)
  "Kota Yogyakarta",
  "Kabupaten Bantul", "Kabupaten Gunungkidul", "Kabupaten Kulon Progo", "Kabupaten Sleman",
  // JAWA TIMUR (38)
  "Kota Surabaya", "Kota Batu", "Kota Blitar", "Kota Kediri", "Kota Madiun", "Kota Malang",
  "Kota Mojokerto", "Kota Pasuruan", "Kota Probolinggo",
  "Kabupaten Bangkalan", "Kabupaten Banyuwangi", "Kabupaten Blitar", "Kabupaten Bojonegoro",
  "Kabupaten Bondowoso", "Kabupaten Gresik", "Kabupaten Jember", "Kabupaten Jombang", "Kabupaten Kediri",
  "Kabupaten Lamongan", "Kabupaten Lumajang", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Malang",
  "Kabupaten Mojokerto", "Kabupaten Nganjuk", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Pamekasan",
  "Kabupaten Pasuruan", "Kabupaten Ponorogo", "Kabupaten Probolinggo", "Kabupaten Sampang", "Kabupaten Sidoarjo",
  "Kabupaten Situbondo", "Kabupaten Sumenep", "Kabupaten Trenggalek", "Kabupaten Tuban", "Kabupaten Tulungagung",
  // BALI (9)
  "Kota Denpasar",
  "Kabupaten Badung", "Kabupaten Bangli", "Kabupaten Buleleng", "Kabupaten Gianyar",
  "Kabupaten Jembrana", "Kabupaten Karangasem", "Kabupaten Klungkung", "Kabupaten Tabanan",
  // NUSA TENGGARA BARAT (10)
  "Kota Mataram", "Kota Bima",
  "Kabupaten Bima", "Kabupaten Dompu", "Kabupaten Lombok Barat", "Kabupaten Lombok Tengah",
  "Kabupaten Lombok Timur", "Kabupaten Lombok Utara", "Kabupaten Sumbawa", "Kabupaten Sumbawa Barat",
  // NUSA TENGGARA TIMUR (22)
  "Kota Kupang",
  "Kabupaten Alor", "Kabupaten Belu", "Kabupaten Ende", "Kabupaten Flores Timur", "Kabupaten Kupang",
  "Kabupaten Lembata", "Kabupaten Malaka", "Kabupaten Manggarai", "Kabupaten Manggarai Barat",
  "Kabupaten Manggarai Timur", "Kabupaten Nagekeo", "Kabupaten Ngada", "Kabupaten Rote Ndao",
  "Kabupaten Sabu Raijua", "Kabupaten Sikka", "Kabupaten Sumba Barat", "Kabupaten Sumba Barat Daya",
  "Kabupaten Sumba Tengah", "Kabupaten Sumba Timur", "Kabupaten Timor Tengah Selatan", "Kabupaten Timor Tengah Utara",
  // KALIMANTAN BARAT (14)
  "Kota Pontianak", "Kota Singkawang",
  "Kabupaten Bengkayang", "Kabupaten Kapuas Hulu", "Kabupaten Kayong Utara", "Kabupaten Ketapang",
  "Kabupaten Kubu Raya", "Kabupaten Landak", "Kabupaten Melawi", "Kabupaten Mempawah",
  "Kabupaten Sambas", "Kabupaten Sanggau", "Kabupaten Sekadau", "Kabupaten Sintang",
  // KALIMANTAN TENGAH (14)
  "Kota Palangka Raya",
  "Kabupaten Barito Selatan", "Kabupaten Barito Timur", "Kabupaten Barito Utara", "Kabupaten Gunung Mas",
  "Kabupaten Kapuas", "Kabupaten Katingan", "Kabupaten Kotawaringin Barat", "Kabupaten Kotawaringin Timur",
  "Kabupaten Lamandau", "Kabupaten Murung Raya", "Kabupaten Pulang Pisau", "Kabupaten Seruyan", "Kabupaten Sukamara",
  // KALIMANTAN SELATAN (13)
  "Kota Banjarmasin", "Kota Banjarbaru",
  "Kabupaten Balangan", "Kabupaten Banjar", "Kabupaten Barito Kuala", "Kabupaten Hulu Sungai Selatan",
  "Kabupaten Hulu Sungai Tengah", "Kabupaten Hulu Sungai Utara", "Kabupaten Kotabaru", "Kabupaten Tabalong",
  "Kabupaten Tanah Bumbu", "Kabupaten Tanah Laut", "Kabupaten Tapin",
  // KALIMANTAN TIMUR (10)
  "Kota Balikpapan", "Kota Bontang", "Kota Samarinda",
  "Kabupaten Berau", "Kabupaten Kutai Barat", "Kabupaten Kutai Kartanegara", "Kabupaten Kutai Timur",
  "Kabupaten Mahakam Ulu", "Kabupaten Paser", "Kabupaten Penajam Paser Utara",
  // KALIMANTAN UTARA (5)
  "Kota Tarakan",
  "Kabupaten Bulungan", "Kabupaten Malinau", "Kabupaten Nunukan", "Kabupaten Tana Tidung",
  // SULAWESI UTARA (15)
  "Kota Manado", "Kota Bitung", "Kota Tomohon", "Kota Kotamobagu",
  "Kabupaten Bolaang Mongondow", "Kabupaten Bolaang Mongondow Selatan", "Kabupaten Bolaang Mongondow Timur",
  "Kabupaten Bolaang Mongondow Utara", "Kabupaten Kepulauan Sangihe", "Kabupaten Kepulauan Siau Tagulandang Biaro",
  "Kabupaten Kepulauan Talaud", "Kabupaten Minahasa", "Kabupaten Minahasa Selatan", "Kabupaten Minahasa Tenggara",
  "Kabupaten Minahasa Utara",
  // GORONTALO (6)
  "Kota Gorontalo",
  "Kabupaten Boalemo", "Kabupaten Bone Bolango", "Kabupaten Gorontalo", "Kabupaten Gorontalo Utara", "Kabupaten Pohuwato",
  // SULAWESI TENGAH (13)
  "Kota Palu",
  "Kabupaten Banggai", "Kabupaten Banggai Kepulauan", "Kabupaten Banggai Laut", "Kabupaten Buol",
  "Kabupaten Donggala", "Kabupaten Morowali", "Kabupaten Morowali Utara", "Kabupaten Parigi Moutong",
  "Kabupaten Poso", "Kabupaten Sigi", "Kabupaten Tojo Una-Una", "Kabupaten Tolitoli",
  // SULAWESI SELATAN (24)
  "Kota Makassar", "Kota Palopo", "Kota Parepare",
  "Kabupaten Bantaeng", "Kabupaten Barru", "Kabupaten Bone", "Kabupaten Bulukumba", "Kabupaten Enrekang",
  "Kabupaten Gowa", "Kabupaten Jeneponto", "Kabupaten Kepulauan Selayar", "Kabupaten Luwu", "Kabupaten Luwu Timur",
  "Kabupaten Luwu Utara", "Kabupaten Maros", "Kabupaten Pangkajene dan Kepulauan", "Kabupaten Pinrang",
  "Kabupaten Sidenreng Rappang", "Kabupaten Sinjai", "Kabupaten Soppeng", "Kabupaten Takalar",
  "Kabupaten Tana Toraja", "Kabupaten Toraja Utara", "Kabupaten Wajo",
  // SULAWESI BARAT (6)
  "Kabupaten Majene", "Kabupaten Mamasa", "Kabupaten Mamuju", "Kabupaten Mamuju Tengah",
  "Kabupaten Pasangkayu", "Kabupaten Polewali Mandar",
  // SULAWESI TENGGARA (17)
  "Kota Kendari", "Kota Baubau",
  "Kabupaten Bombana", "Kabupaten Buton", "Kabupaten Buton Selatan", "Kabupaten Buton Tengah",
  "Kabupaten Buton Utara", "Kabupaten Kolaka", "Kabupaten Kolaka Timur", "Kabupaten Kolaka Utara",
  "Kabupaten Konawe", "Kabupaten Konawe Kepulauan", "Kabupaten Konawe Selatan", "Kabupaten Konawe Utara",
  "Kabupaten Muna", "Kabupaten Muna Barat", "Kabupaten Wakatobi",
  // MALUKU (11)
  "Kota Ambon", "Kota Tual",
  "Kabupaten Buru", "Kabupaten Buru Selatan", "Kabupaten Kepulauan Aru", "Kabupaten Kepulauan Tanimbar",
  "Kabupaten Maluku Barat Daya", "Kabupaten Maluku Tengah", "Kabupaten Maluku Tenggara",
  "Kabupaten Seram Bagian Barat", "Kabupaten Seram Bagian Timur",
  // MALUKU UTARA (10)
  "Kota Ternate", "Kota Tidore Kepulauan",
  "Kabupaten Halmahera Barat", "Kabupaten Halmahera Selatan", "Kabupaten Halmahera Tengah",
  "Kabupaten Halmahera Timur", "Kabupaten Halmahera Utara", "Kabupaten Kepulauan Sula",
  "Kabupaten Pulau Morotai", "Kabupaten Pulau Taliabu",
  // PAPUA (29)
  "Kota Jayapura",
  "Kabupaten Asmat", "Kabupaten Biak Numfor", "Kabupaten Boven Digoel", "Kabupaten Deiyai",
  "Kabupaten Dogiyai", "Kabupaten Intan Jaya", "Kabupaten Jayapura", "Kabupaten Jayawijaya",
  "Kabupaten Keerom", "Kabupaten Kepulauan Yapen", "Kabupaten Lanny Jaya", "Kabupaten Mamberamo Raya",
  "Kabupaten Mamberamo Tengah", "Kabupaten Mappi", "Kabupaten Merauke", "Kabupaten Mimika",
  "Kabupaten Nabire", "Kabupaten Nduga", "Kabupaten Paniai", "Kabupaten Pegunungan Bintang",
  "Kabupaten Puncak", "Kabupaten Puncak Jaya", "Kabupaten Sarmi", "Kabupaten Supiori",
  "Kabupaten Tolikara", "Kabupaten Waropen", "Kabupaten Yahukimo", "Kabupaten Yalimo",
  // PAPUA BARAT (13)
  "Kota Sorong",
  "Kabupaten Fakfak", "Kabupaten Kaimana", "Kabupaten Manokwari", "Kabupaten Manokwari Selatan",
  "Kabupaten Maybrat", "Kabupaten Pegunungan Arfak", "Kabupaten Raja Ampat", "Kabupaten Sorong",
  "Kabupaten Sorong Selatan", "Kabupaten Tambrauw", "Kabupaten Teluk Bintuni", "Kabupaten Teluk Wondama",
  // PAPUA SELATAN (4)
  "Kabupaten Asmat", "Kabupaten Boven Digoel", "Kabupaten Mappi", "Kabupaten Merauke",
  // PAPUA TENGAH (8)
  "Kabupaten Deiyai", "Kabupaten Dogiyai", "Kabupaten Intan Jaya", "Kabupaten Mimika",
  "Kabupaten Nabire", "Kabupaten Paniai", "Kabupaten Puncak", "Kabupaten Puncak Jaya",
  // PAPUA PEGUNUNGAN (8)
  "Kabupaten Jayawijaya", "Kabupaten Lanny Jaya", "Kabupaten Mamberamo Tengah", "Kabupaten Nduga",
  "Kabupaten Pegunungan Bintang", "Kabupaten Tolikara", "Kabupaten Yahukimo", "Kabupaten Yalimo",
  // PAPUA BARAT DAYA (6)
  "Kota Sorong", "Kabupaten Maybrat", "Kabupaten Raja Ampat", "Kabupaten Sorong",
  "Kabupaten Sorong Selatan", "Kabupaten Tambrauw"
].sort();

// Daftar Bank di Indonesia (termasuk bank digital)
export const indonesiaBanks = [
  // Bank Konvensional
  "Bank Central Asia (BCA)",
  "Bank Mandiri",
  "Bank Rakyat Indonesia (BRI)",
  "Bank Negara Indonesia (BNI)",
  "Bank CIMB Niaga",
  "Bank Danamon",
  "Bank Permata",
  "Bank Panin",
  "Bank OCBC NISP",
  "Bank Maybank Indonesia",
  "Bank UOB Indonesia",
  "Bank HSBC Indonesia",
  "Bank DBS Indonesia",
  "Bank Mega",
  "Bank Bukopin",
  "Bank BTN",
  "Bank Sinarmas",
  "Bank Commonwealth",
  "Bank Victoria",
  "Bank Artha Graha",
  "Bank BJB (Jabar Banten)",
  "Bank DKI",
  "Bank Jatim",
  "Bank Jateng",
  "Bank Sumut",
  "Bank Nagari",
  "Bank Riau Kepri",
  "Bank Sumsel Babel",
  "Bank Lampung",
  "Bank Kalbar",
  "Bank Kalsel",
  "Bank Kaltim",
  "Bank Sulselbar",
  "Bank Sulut",
  "Bank NTB",
  "Bank NTT",
  "Bank Maluku",
  "Bank Papua",
  "Bank Aceh",
  "Bank Bengkulu",
  "Bank Jambi",
  // Bank Syariah
  "Bank Syariah Indonesia (BSI)",
  "Bank Muamalat",
  "Bank Mega Syariah",
  "Bank BCA Syariah",
  "Bank BTPN Syariah",
  // Bank Digital
  "Bank Jago",
  "Bank Neo Commerce (BNC)",
  "Allo Bank",
  "Bank Raya (BRI Digital)",
  "Seabank",
  "Bank Saqu (BCA Digital)",
  "Line Bank (KEB Hana)",
  "Blu by BCA Digital",
  "Superbank",
  "Motion Banking (MNC)",
  "Wokee (Bukopin)",
  "Digibank by DBS",
  "TMRW by UOB",
  "Bank Amar",
  "OK Bank",
  // E-Wallet (yang bisa terima transfer)
  "OVO",
  "GoPay",
  "DANA",
  "ShopeePay",
  "LinkAja",
  "DOKU",
  "PayPal",
  "Jenius (BTPN)",
  "Flip",
  "Kredivo",
  "Akulaku"
].sort();

